Repository FBDY/bb-blocks, pull requests merged in 2019-04, with the labels that each got.

#20 Add send message and wait blocks
  blocks_vertical/default_toolbox.js
  blocks_vertical/event.js
  msg/js/en.js
  msg/json/en.json
  msg/messages.js
Labels: enhancement

#18 Stretch X and Y blocks
  blocks_vertical/looks.js
  msg/js/en.js
  msg/json/en.json
  msg/messages.js
  msg/scratch_msgs.js
Labels: good first issue

#21 Add "translations" for stretch x/y feature
  msg/json/en.json
Labels: bug
